Repository rbatsenko/hangs-free, pull requests merged in 2025-06, with the labels that each got.

#13 ✨ Add Manual Dark Mode Switcher
  README.md
  app.json
  app/(tabs)/lift.tsx
  app/(tabs)/settings.tsx
  app/_layout.tsx
  components/ui/IconSymbol.tsx
  components/ui/SegmentedControl.tsx
  components/ui/ThemeSelector.tsx
  components/ui/__tests__/ThemeSelector.test.tsx
  components/ui/index.ts
  constants/navigation-themes.ts
  contexts/ThemeContext.tsx
  hooks/__tests__/useColorScheme.test.tsx
  hooks/useColorScheme.ts
  jest.setup.js
  package-lock.json
  package.json
Labels: feature, improvement

#15 Fix Tindeq Scan
  hooks/useTindeq.ts
Labels: bug

#20 feat: Add automated changelog and release system
  .github/workflows/release-please.yml
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  hooks/__tests__/useColorScheme.test.tsx
  package.json
  release-please-config.json
Labels: documentation, improvement
